TourDuLichSite/Controllers/DiaDiemController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tour.DAO;

namespace TourDuLichSite.Controllers
{
    public class DiaDiemController : Controller
    {
        DiaDiemDAO ddd = new DiaDiemDAO();
        // GET: DiaDiem
        public ActionResult Index()
        {
            List<dynamic> listResults = ddd.GetLDD();
            var objOld = JsonConvert.SerializeObject(listResults);
            var obj = JsonConvert.DeserializeObject<List<DiaDiemView>>(objOld);
            ViewBag.listTemp = obj;
            return View();
        }
        [HttpGet]
        [Route("GetAllDiaDiemDen")]
        public JsonResult GetAllDiaDiemDen()
        {
            var getDDD = ddd.GetListDiaDiem();
            return Json(getDDD, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [Route("GetOneDiaDiemDen")]
        public JsonResult GetOneDiaDiemDen(int MaDiaDiem)
        {
            var getDDD = ddd.GetDiaDiem(MaDiaDiem);
            return Json(getDDD, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("Create")]
        public JsonResult Create(DIADIEM D)
        {
            return Json(ddd.AddDiaDiem(D), JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Route("Update")]
        public JsonResult Update(DIADIEM D, int MaDiaDiem)
        {
            return Json(ddd.Edit(D, MaDiaDiem), JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        [Route("Delete")]
        public JsonResult Delete(DIADIEM D, int MaDiaDiem)
        {
            return Json(ddd.Delete(D, MaDiaDiem), JsonRequestBehavior.AllowGet);

        }
    }
}

TourDuLichSite/Controllers/DoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tour.DAO;using Tour.BUS;
using Newtonsoft.Json;

namespace TourDuLichSite.Controllers
{
    public class DoanController : Controller
    {
        DoanDAO dd = new DoanDAO();
        BookingDAO bd = new BookingDAO();
        // GET: Doan
        public ActionResult Index()
        {
            List<dynamic> listResults = dd.getListDoanW();
            var objOld = JsonConvert.SerializeObject(listResults);
            var obj = JsonConvert.DeserializeObject<List<DoanView>>(objOld);
            ViewBag.listTemp = obj;
            return View();
        }
        [HttpGet]
        [Route("GetOneDoan")]
        public JsonResult GetOneDoan(int MaDOANDL)
        {
            var getDoan = dd.GetOneDoan(MaDOANDL);
            return Json(getDoan, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [Route("GetAllDoan")]
        public JsonResult GetAllDoan()
        {
            var getDoan = dd.getall();
            return Json(getDoan, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [Route("GetListKH")]
        public JsonResult GetListKH(int MaDOANDL)
        {
            var getKH = bd.GetDetailW(MaDOANDL);
            return Json(getKH, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Route("Create")]
        public JsonResult Create(DOANDL D)
        {

            return Json(dd.Add(D), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Route("Update")]
        public JsonResult Update(DOANDL D, int MaDOANDL)
        {
            return Json(dd.EditW(D, MaDOANDL), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Route("Delete")]
        public JsonResult Delete(int MaDOANDL)
        {
            return Json(dd.Delete(MaDOANDL), JsonRequestBehavior.AllowGet);

        }
        public ActionResult Detail(int MaDOANDL)
        {
            List<dynamic> listResults = dd.GetDDetailW(MaDOANDL);
            var objOld = JsonConvert.SerializeObject(listResults);
            var obj = JsonConvert.DeserializeObject<List<DoanView>>(objOld);
            ViewBag.listTemp = obj;
            var GetDoan = dd.GetOneDoan(MaDOANDL);
            ViewBag.listOneDoan = GetDoan;

            var getListKHDK = bd.GetDetailW(MaDOANDL);
            //convert List<dynamic> sang json
            var getListKHDKobjOld = JsonConvert.SerializeObject(getListKHDK);
            //convert json sang List<View>
            var getListKHDKobj = JsonConvert.DeserializeObject<List<BookingView>>(getListKHDKobjOld);
            ViewBag.listKHDK = getListKHDKobj;
            return View();
        }
        
    }
}

TourDuLichSite/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tour.DAO;using Tour.BUS;
using Newtonsoft.Json;

namespace TourDuLichSite.Controllers
{
    public class NhanVienController : Controller
    {
        NhanVienDAO nvd = new NhanVienDAO();
        // GET: NhanVien
        public ActionResult Index()
        {
            List<dynamic> listResults = nvd.GetListNhanVienW();
            var objOld = JsonConvert.SerializeObject(listResults);
            var obj = JsonConvert.DeserializeObject<List<NhanVienView>>(objOld);
            ViewBag.listTemp = obj;
            return View();
        }
        [HttpGet]
        [Route("GetOneNhanVien")]
        public JsonResult GetOneNhanVien(int MaNV)
        {
            var getNhanVien = nvd.GetListDetailsNhanVienW(MaNV);
            return Json(getNhanVien, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        [Route("GetAllNV")]
        public JsonResult GetAllNV()
        {
            var getTour = nvd.GetAllNhanVien();
            return Json(getTour, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [Route("Create")]
        public JsonResult Create(NHANVIEN NV)
        {

            return Json(nvd.ThemNhanVien(NV), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Route("Update")]
        public JsonResult Update(NHANVIEN NV, int MaNV)
        {
            return Json(nvd.SuaNhanVien(NV, MaNV), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Route("Delete")]
        public JsonResult Delete(int MaNV)
        {
            return Json(nvd.XoaNhanVien(MaNV), JsonRequestBehavior.AllowGet);

        }

    }
}

TourDuLichSite/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TourDuLichSite.Controllers
{
    public class ThongKeController : Controller
    {
        // GET: ThongKe
        public ActionResult Index()
        {
            return View();
        }
    }
}

TourDuLichSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="description" content="Portal - Bootstrap 5 Admin Dashboard Template For Developers">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">
    <link rel="shortcut icon" href="~/Content/images/420-4207383_icon-of-signs-representing-campus-tour-take-a.png">

    <!-- FontAwesome JS-->
    <script defer src="~/Content/plugins/fontawesome/js/all.min.js"></script>
    <!-- App CSS -->
    <link id="theme-style" rel="stylesheet" href="~/Content/css/portal.css">
    <link id="theme-style" rel="stylesheet" href="~/Content/css/preloader.css">

    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/sweetalert.min.js"></script>

    <script>setTimeout(function () {
            $('.loader-bg').fadeToggle();
        }, 1000);</script>

</head>

<body>
    <!-- Preloader -->
    <div class="loader-bg">
        <div class="loader-p"></div>
    </div>

    <div class="app">

        <header class="app-header fixed-top">
            <div class="app-header-inner">
                <div class="container-fluid py-2">
                    
                </div><!--//container-fluid-->
            </div><!--//app-header-inner-->
            <div id="app-sidepanel" class="app-sidepanel">
                <div id="sidepanel-drop" class="sidepanel-drop"></div>
                <div class="sidepanel-inner d-flex flex-column">
                    <a href="#" id="sidepanel-close" class="sidepanel-close d-xl-none">&times;</a>
                    <div class="app-branding">
                        <a><span class="logo-text">QUẢN LÝ TOUR</span></a>

                    </div><!--//app-branding-->

                    <nav id="app-nav-main" class="app-nav app-nav-main flex-grow-1">
                        <ul class="app-menu list-unstyled accordion" id="menu-accordion">
                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Tổng quan")) {@Html.Encode("active"); }}" href="@Url.Action("Index", "ThongKe")">
                                    <span class="nav-link-text">Tổng quan</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Tour")) {@Html.Encode("active"); }}" href="@Url.Action("Index","Tour")">
                                    <span class="nav-link-text">Tour</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Đoàn du lịch")) {@Html.Encode("active"); }}" href="@Url.Action("Index","Doan")">
                                    <span class="nav-link-text">Đoàn du lịch</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Nhân viên")) {@Html.Encode("active"); }}" href="@Url.Action("Index","NhanVien")">
                                    <span class="nav-link-text">Nhân viên</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Khách hàng")) {@Html.Encode("active"); }}" href="@Url.Action("Index","KhachHang")">
                                    <span class="nav-link-text">Khách hàng</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("LoaiHinh")) {@Html.Encode("active"); }}" href="@Url.Action("Index","LoaiHinh")">
                                    <span class="nav-link-text">Loại hình du lịch</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->

                            <li class="nav-item">
                                <a class="nav-link @{if (ViewBag.Title.Equals("Địa điểm")) {@Html.Encode("active"); }}" href="@Url.Action("Index","DiaDiem")">
                                    <span class="nav-link-text">Địa điểm</span>
                                </a><!--//nav-link-->
                            </li><!--//nav-item-->



                        </ul><!--//app-menu-->
                    </nav><!--//app-nav-->
                    <div class="app-sidepanel-footer">
                        <nav class="app-nav app-nav-footer">
                            <ul class="app-menu footer-menu list-unstyled">
                                <li class="nav-item">
                                    <span class="nav-link-text"></span>
                                </li><!--//nav-item-->
                            </ul><!--//footer-menu-->
                        </nav>
                    </div><!--//app-sidepanel-footer-->

                </div><!--//sidepanel-inner-->
            </div><!--//app-sidepanel-->
        </header><!--//app-header-->

        <div>
            @RenderBody()
        </div>



        <!-- Javascript -->
        <script src="~/Content/plugins/popper.min.js"></script>
        <script src="~/Content/plugins/bootstrap/js/bootstrap.min.js"></script>

        <!-- Charts JS -->
        <script src="~/Content/plugins/chart.js/chart.min.js"></script>
        <script src="~/Content/js/index-charts.js"></script>

        <!-- Page Specific JS -->
        <script src="~/Content/js/app.js"></script>
        <script src="~/Content/js/jquery.min.js"></script>

    </div>
</body>
</html>